export const REGISTER_USER = 'REGISTER_USER'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOAD_USER = 'LOAD_USER'
export const LOAD_FAILED = 'LOAD_FAILED'
export const LOGOUT = 'LOGOUT'